version: 2
updates:
  # Mobile dependencies
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "phuhokhongtien"
    labels:
      - "dependencies"
      - "mobile"
    commit-message:
      prefix: "chore(mobile)"
      include: "scope"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore major version updates for React Native
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
  
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "phuhokhongtien"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "phuhokhongtien"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
  
  # Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "phuhokhongtien"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
