version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: github_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - github_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: github_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - github_network

  # Backend API (optional, uncomment when backend Dockerfile is ready)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: github_backend
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=postgres
  #     - REDIS_HOST=redis
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - github_network

volumes:
  postgres_data:
  redis_data:

networks:
  github_network:
    driver: bridge
